### ISSUE TITLE
Cloud Storage

### ISSUE THREAD

**Issue by jaikishantulswani** [nsonaniya2010/SubDomainizer#1]
It would be good if you add some more cloud storage services like digitaloceanspaces.com,windows.net,storage.googleapis.com etc.

**Comment by nsonaniya2010** [comment]
Sure I will do that :) Thanks

**Comment by nsonaniya2010** [comment]
Added support for following Cloud Services:
```
1. Amazon S3 bucket
2. Amazon Cloudfront
3. Google cloud services
4. Microsoft Azure
5. RackCDN
6. Dreamhost
```

Do let me know if any other services are there to add.

Thanks for your contribution.
