### ISSUE TITLE
Add flag for ignoring SSL errors

### ISSUE THREAD

**Issue by williamoverton** [nsonaniya2010/SubDomainizer#10]
**Describe the bug**
When testing against an internal site with invalid SSL I get this error:
`An error occured while fetching URL, Might be server is down, or domain does not exist, Please check!`

**Suggested Fix**
Add a flag which ignores all ssl errors (-k in this example)
1. Have site with invalid ssl
2. Run `python3 SubDomainizer.py -u -k https://mysite.com`
3. ???
4. Profit

**Comment by nsonaniya2010** [comment]
Let me know if this fixes the problem.
