### ISSUE TITLE
Issue with termcolor

### ISSUE THREAD

**Issue by jrwalzer** [nsonaniya2010/SubDomainizer#11]
**Describe the bug**
When I run python3 SubDomainizer.py -h, I get the following error message:

Traceback (most recent call last):
  File "SubDomainizer.py", line 13, in <module>
    import termcolor
ImportError: No module named 'termcolor'

I have verified that the module 'termcolor' is installed

**Comment by nsonaniya2010** [comment]
Try to install requirements using:

```
pip3 install -r requirements.txt
```
and then run.

**Comment by jrwalzer** [comment]
Thx - that worked
