### ISSUE TITLE
TypeError: zip argument #1 must support iteration

### ISSUE THREAD

**Issue by robdollard** [nsonaniya2010/SubDomainizer#12]
By switched on search in GitHub such error appears here
![image](https://user-images.githubusercontent.com/40629638/55380929-2d1fc900-553b-11e9-811c-25495c7d7cf0.png)

**Comment by nsonaniya2010** [comment]
I am looking into it.
Thanks for raising it.

**Comment by nsonaniya2010** [comment]
Let me know what command invoked it?

**Comment by robdollard** [comment]
> Дайте мне знать, какая команда вызвала его?

python3 SubDomainizer.py -u https://lob.com -gt <token> -g

**Comment by nsonaniya2010** [comment]
Giving me proper results.

![xxx](https://user-images.githubusercontent.com/13208587/55391719-8bf33b80-5557-11e9-9cf0-1ddc0d66bc3d.png)
![Screenshot from 2019-04-02 14-53-37](https://user-images.githubusercontent.com/13208587/55391720-8d246880-5557-11e9-8b5f-f7be21f7c799.png)

**Comment by robdollard** [comment]
Yes, On Kali Linux, everything worked with the same parameters.
![image](https://user-images.githubusercontent.com/40629638/55393045-e7bcc500-5555-11e9-8e29-67e4e28f3071.png)
Strange, but you have found more subdomains.
The problem is that I ran on Parrot? but what could go wrong there

**Comment by nsonaniya2010** [comment]
Updated tool to get more results, please pull new one from repo.

Closing it as it is some issue of your OS.
