### ISSUE TITLE
Suggesting optional print of where the secretList items have been found

### ISSUE THREAD

**Issue by fuomag9** [nsonaniya2010/SubDomainizer#13]
**Is your feature request related to a problem? Please describe.**
I know what the secrets are but I need to know where were they found so I can remove the data leak from my server

**Describe the solution you'd like**
I'd like to see where the items in secretList are found, to make it easier to understand which files/data is their source

**Comment by nsonaniya2010** [comment]
I will see what I can do here.

**Comment by AnotherWayIn** [comment]
+1

**Comment by unethicalnoob** [comment]
I tried to make it work but I couldn't. Looking forward to the feature. I have found a lot of keys lately

**Comment by nsonaniya2010** [comment]
@unethicalnoob Can you please create a separate issue, with some examples?

**Comment by hiddengearz** [comment]
I would also love to see this feature aadded, the script prints out an API key e.g "-Api-Key': 'xxxxxxxxx' but I have no idea where it came from and have to spend time shifting through js files to find it.

**Comment by hiddengearz** [comment]
Spent like 2 hours trying to reverse engineer this to get url's to print with the keys and couldn't get it working, roadblock after road block and I just gave up.

Seems like a good chunk of the code needs to be rewritten.

**Comment by nsonaniya2010** [comment]
I'll start to rewrite code this week.

**Comment by spazbg** [comment]
I really need to know where is leaking from those keys... only KEY=&^%$&^%... it's not enough information, except that the tool is cool 🥇

**Comment by pdelteil** [comment]
Same here, not being able to find where the keys are stored.

**Comment by nsonaniya2010** [comment]
I've fixed this one and testing it and will upload it by EOD today. You may create pull request to improve it.

**Comment by nsonaniya2010** [comment]
Guys this feature has been added. Please try this as well as SAN feature.

**Comment by nsonaniya2010** [comment]
Closing this one.

**Comment by spazbg** [comment]
> Guys this feature has been added. Please try this as well as SAN feature.

Let me see :)

**Comment by pdelteil** [comment]
Hello @nsonaniya2010. 

Thanks for the update. 

In my case the result of the keys found says 'Inline' this means it was found on the main page of the domain?

**Comment by nsonaniya2010** [comment]
Yes.
