### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by sk3lk0** [nsonaniya2010/SubDomainizer#16]
i use mitm for check requests, so sometimes script make request with joined strings. 
i try using sript for github.com , and i see this:

172.18.0.11:37246: GET https://github.com/
200 OK 39.23k
172.18.0.11:37250: GET https://github.com/
200 OK 39.25k
GET https://github.githubassets.com/assets/compat-bootstrap-edde9aec.jshttps://github.githubassets.com/assets/compat-bootstrap-edde9aec.js
404 Not Found 30b
GET https://github.githubassets.com/assets/github-bootstrap-e9911286.js
200 OK 122.5k
GET https://github.githubassets.com/assets/compat-bootstrap-edde9aec.js
200 OK 9.42k
GET https://github.githubassets.com/assets/frameworks-564f5a6e.jshttps://github.githubassets.com/assets/frameworks-564f5a6e.js
404 Not Found 30b
GET https://github.githubassets.com/assets/frameworks-564f5a6e.js
200 OK 48.33k
GET https://github.githubassets.com/assets/github-bootstrap-e9911286.jshttps://github.githubassets.com/assets/github-bootstrap-e9911286.js
404 Not Found 30b

So few request contains of 2 urls

**Comment by nsonaniya2010** [comment]
Hi,
can you provide the command on terminal you used?

**Comment by sk3lk0** [comment]
python3.6 SubDomainizer.py -u https://github.com/ -k

**Comment by nsonaniya2010** [comment]
This should be fixed please check and let me know.
