### ISSUE TITLE
Js url print + threaded ?

### ISSUE THREAD

**Issue by dmatrixx** [nsonaniya2010/SubDomainizer#19]
Hi ,

Thanks for the great tool .

- Given the tool fetches many js files , regex prints the secrets on hits but does not print the URL where it was found . Printing js url wouldn't be a good enhancement ?  it can save extra effort back-tracing the url .

- It is slow even when given list of 10-20 domains . Can multiprocessing be applied here to make it faster ? 

Thanks

**Comment by nsonaniya2010** [comment]
I think #13 is same as yours.
