### ISSUE TITLE
Append http/https to subdomain list

### ISSUE THREAD

**Issue by Regala** [nsonaniya2010/SubDomainizer#2]
Would be great if when reading from the subdomain list http or https is pre-appended, so it's easier to import from other tools. 

Will be happy to send a PR later if needed.

**Comment by nsonaniya2010** [comment]
Ok I will add that.

thanks

**Comment by s0md3v** [comment]
Nope, don't do that. There's a difference between a domain and a URL and we should maintain that.
What if I want to perform a port scan on the results? or whois look up?
Also, making request to every subdomain to see if it uses http and https is overkill.
