### ISSUE TITLE
SubDomainizer error on RPi3

### ISSUE THREAD

**Issue by spazbg** [nsonaniya2010/SubDomainizer#24]
![image](https://user-images.githubusercontent.com/22222777/91835864-a3ee5380-ec52-11ea-8639-0863fe73f8ec.png)
I am getting this error on Raspberry Pi 3. Any ideas on how to fix it?

**Comment by nsonaniya2010** [comment]
This may be due to your System configuration.

You can change the line (or similar lines):

> Line 647 of code

```python
jsthread = ThreadPool(300)
```
to

```python
jsthread = ThreadPool(8)
```

Let me know if that doesn't solve your issue.
