### ISSUE TITLE
savesecretsresults() doesn't get called 

### ISSUE THREAD

**Issue by zar-zar** [nsonaniya2010/SubDomainizer#25]
Hi,

Firstly, a great tool, so glad I found it!

I have noticed that `savesecretsresults()` isn't begin called in the SubDomainizer.py. As a result, nothing is getting saved to `-sop --SECRETOP`. 
https://github.com/nsonaniya2010/SubDomainizer/blob/ea9a16639487d28cac2479a624ac789004bdb9c5/SubDomainizer.py#L699-L705

I don't like to raise an issue without giving a possible solution but unfortunately, my coding isn't up to scratch.

**Comment by nsonaniya2010** [comment]
Will check this out.

**Comment by nsonaniya2010** [comment]
Fixed. Please confirm.
