### ISSUE TITLE
S3 Bucket Issue

### ISSUE THREAD

**Issue by jaikishantulswani** [nsonaniya2010/SubDomainizer#3]
Hello @nsonaniya2010 
SubDomainizer is not parsing amazon bucket from url as the source is like

`
<a href="https://example.com" target="NEW"><img src="https://s3-us-west-2.amazonaws.com/domain/image.jpg"></a>
`

**Comment by nsonaniya2010** [comment]
It just fetch urls from js.
I will add <a href> tag and <img src> tag to fetch data from them also.

Thanks for your contribution.

**Comment by nsonaniya2010** [comment]
Fixed man, Download new version and let me know feedback.

**Comment by jaikishantulswani** [comment]
Hello @nsonaniya2010 ,
Its working :100:

**Comment by nsonaniya2010** [comment]
Thanks for confirmation :)
