### ISSUE TITLE
Some urls cause Domainizer to totally freeze

### ISSUE THREAD

**Issue by l0nenul** [nsonaniya2010/SubDomainizer#30]
This is a really annoying bug, after I gather subdomains and put the URLS in a list to scan them, subdomainizer completely freezes at specific urls for whatever reasons despite being alive hosts, I delete the URL from the txt file that's causing this and rescan, another URL that causes the tool to completely freeze and I had to remove that too..etc until the output finally shows when there are no more URLs causing a permanent freeze

other than that the tool is an exception and is very useful despite simplicity, thank you very much for publicly posting the project

**Comment by nsonaniya2010** [comment]
Thanks.
Have you tried debugging the code in case of that specific URL. If not please try to get me one example so that I can take a look of the issue and fix it.

**Comment by nsonaniya2010** [comment]
So, there is no timeout set on requesting a page/resource, this is the most probable reason for freezing the tool. I will add a timeout and push update.

**Comment by neerajsonaniya** [comment]
Fixed the issue in latest commit.

**Comment by nsonaniya2010** [comment]
Fixed issue in latest commit.
