### ISSUE TITLE
no module named termcolor

### ISSUE THREAD

**Issue by codefaztaz** [nsonaniya2010/SubDomainizer#38]
**Describe the bug**

**To Reproduce**

y run the tool sudo python3 SubDomainizer.py -u target.com

I get

Traceback (most recent call last):
  File "/home/bug/Desktop/tool2/SubDomainizer/SubDomainizer.py", line 13, in <module>
    import termcolor
ModuleNotFoundError: No module named 'termcolor'

the module is already installed in my linux mint.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nsonaniya2010** [comment]
Please install the requirements using:

`pip install -r requirements.txt`
