### ISSUE TITLE
Log results in different files

### ISSUE THREAD

**Issue by Regala** [nsonaniya2010/SubDomainizer#4]
Currently the output is logged into one file which we can specify with the "-o" flag. Ideally, we could use that same flag and two different files would be generated: one with the results from subdomains another  with cloud storage results. The names could be pre-appended with the parameter from the output flag.

This would make much easier to parse results from the tool and integration into different workflows.

Cheres

**Comment by nsonaniya2010** [comment]
Updated.
Use the '-cop' or '--cloudop' with file name to save the results.

**Comment by wingzRED** [comment]
Just to expand on this, would also be nice to have a third output file for GitHub secrets, maybe `-gop` ?

**Comment by nsonaniya2010** [comment]
Sure @wingzRED. Will add it by this weekend.

**Comment by nsonaniya2010** [comment]
@wingzRED Made the changes to the latest version. Please check and update the ticket.

**Comment by wingzRED** [comment]
Yeah confirmed its working, cheers @nsonaniya2010 !

**Comment by nsonaniya2010** [comment]
Thanks for the confirmation!!
