### ISSUE TITLE
envalid escape sequence error

### ISSUE THREAD

**Issue by jaikishantulswani** [nsonaniya2010/SubDomainizer#7]
Hello @nsonaniya2010 ,
Getting this after scanning 10+ subdomains using list function:

`Searching for External Javascript links in page.....
Successfully got all the external js links
SubDomainizer.py:132: DeprecationWarning: invalid escape sequence '\|'
  content = unquote(requests.get(js).content.decode('unicode-escape'))`

`Traceback (most recent call last):
  File "SubDomainizer.py", line 360, in <module>
    subextractor(compiledRegexCloud, compiledRegexSecretList, compiledRegexDomain,compiledRegexIP, i)
  File "SubDomainizer.py", line 290, in subextractor
    threads = ThreadPool(300)
  File "/usr/lib/python3.7/multiprocessing/dummy/__init__.py", line 124, in Pool
    return ThreadPool(processes, initializer, initargs)
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 802, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 176, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 241, in _repopulate_pool
    w.start()
  File "/usr/lib/python3.7/multiprocessing/dummy/__init__.py", line 51, in start
    threading.Thread.start(self)
  File "/usr/lib/python3.7/threading.py", line 847, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
`

**Comment by nsonaniya2010** [comment]
Hi,
This is not the issue of number of items in given input list. Due to some decoding issue this issue persist.

**Comment by nsonaniya2010** [comment]
Is that fixed?

**Comment by jaikishantulswani** [comment]
Hey @nsonaniya2010 
Now its getting stuck on random domain when giving a list of domain, not completing.

**Comment by nsonaniya2010** [comment]
Let me know the screenshot so that I can understand the problem clearly.

**Comment by jaikishantulswani** [comment]
@nsonaniya2010 

It getting stuck like 

`
domain.example.com
Searching for Inline Javascripts.....
Successfully got all the Inline Scripts.
Searching for External Javascript links in page.....
Successfully got all the external js links
`

**Comment by nsonaniya2010** [comment]
Hi,
this is due to Internet connectivity.
please check your internet connection.

**Comment by jaikishantulswani** [comment]
@nsonaniya2010 
This may be but every other thing is working and I am getting stuck only on this issue.

**Comment by jaikishantulswani** [comment]
@nsonaniya2010 is it possible to get result of every domain just after when we use switch -l

1.example.com
Searching for Inline Javascripts.....
Successfully got all the Inline Scripts.
Searching for External Javascript links in page.....
Successfully got all the external js links
Finding Subdomains and cloud data of given domain in all Javascript files...
Searching completed...
**Results**
